version: '3.6'

services:

  node-km-api:
    # image: 192.168.178.4:5000/node-km-api:0.0.1
    build: ./node-km-api
    restart: always
    depends_on:
      - mysql
      - mongo
    env_file:
      - ./secrets/mysql/.env
      - ./secrets/mongo/.env
      - ./secrets/api/.env
    environment:
      DB_HOST: mysql
      MONGO_HOST: mongo
    ports:
      - 3005:3005

  mysql:
    image: mariadb
    restart: always
    env_file:
      - ./secrets/mysql/.env
    volumes:
      - /d/workspace/data/mysql/kmregistration:/var/lib/mysql

  adminer:
    image: adminer:4.6.3
    restart: always
    depends_on:
      - mysql
    ports:
      - 9000:8080

  mongo:
    image: mongo
    restart: always
    env_file:
      - ./secrets/mongo/.env
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 9001:8081
    env_file:
      - ./secrets/mongo/.env
    depends_on:
      - mongo
